---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingchen.
--- DateTime: 2022/6/8 19:07
---
local voucherId = ARGV[1]   -- 优惠券id
local userId = ARGV[2]  -- 用户id
local orderId = ARGV[3]  -- 订单id
local stockKey = 'seckill:stock:' .. voucherId  -- 库存id
local orderKey = 'seckill:order:' .. voucherId  -- 订单id
-- 判断库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0) then
    -- 库存不足，返回1
    return 1
end
-- 判断用户是否已下过单
if(redis.call('sismember',orderKey,userId) == 1) then
    -- 存在，说明重复下单了，返回2
    return 2
end
-- 扣库存
redis.call('incrby',stockKey,-1)
-- 下单
redis.call('sadd',orderKey,userId)
-- 发送消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)  -- id：对应voucherOrder的id属性
return 0